version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install

android:
  docker:
    - image: circleci/android:api-27-node8-alpha
  steps:
    - checkout
    - run: npm install
    - run: cd android && ./gradlew assembleRelease

ios:
  macos:
    xcode: '9.4.1'
  shell: /bin/bash --login -o pipefail
  steps:
    - checkout
    - run: npm install
    - run: xcodebuild -project ios/barhunt.xcworkspace -scheme 'barhunt' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhoneX'

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
        requires:
          - node
      - ios:
        requires:
          - node
